version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular_frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - backend_default
    environment:
      - API_URL=http://laravel_nginx:80

networks:
  backend_default:
    external: false